// Built-in core sound pack mapping voice-soundboard procedural effects

import type { SoundPackManifest } from './types.js';

/** Core sound pack with voice-soundboard procedural effect mappings. */
export const CORE_SOUND_PACK: SoundPackManifest = {
  name: 'core',
  version: '1.0.0',
  description: 'Built-in sound effects mapped to voice-soundboard procedural generation',
  author: 'ai-rpg-engine',
  entries: [
    // UI chimes
    {
      id: 'ui_notification',
      tags: ['ui', 'alert'],
      domain: 'sfx',
      intensity: 'low',
      mood: ['neutral'],
      durationClass: 'oneshot',
      cooldownMs: 1000,
      variants: [],
      source: 'voice-soundboard',
      voiceSoundboardEffect: 'chime_notification',
    },
    {
      id: 'ui_success',
      tags: ['ui', 'positive'],
      domain: 'sfx',
      intensity: 'low',
      mood: ['positive', 'triumph'],
      durationClass: 'oneshot',
      cooldownMs: 1000,
      variants: [],
      source: 'voice-soundboard',
      voiceSoundboardEffect: 'chime_success',
    },
    {
      id: 'ui_error',
      tags: ['ui', 'negative'],
      domain: 'sfx',
      intensity: 'low',
      mood: ['negative', 'failure'],
      durationClass: 'oneshot',
      cooldownMs: 1000,
      variants: [],
      source: 'voice-soundboard',
      voiceSoundboardEffect: 'chime_error',
    },
    {
      id: 'ui_attention',
      tags: ['ui', 'alert'],
      domain: 'sfx',
      intensity: 'medium',
      mood: ['neutral'],
      durationClass: 'oneshot',
      cooldownMs: 2000,
      variants: [],
      source: 'voice-soundboard',
      voiceSoundboardEffect: 'chime_attention',
    },
    // UI interaction sounds
    {
      id: 'ui_click',
      tags: ['ui', 'input'],
      domain: 'sfx',
      intensity: 'low',
      mood: ['neutral'],
      durationClass: 'oneshot',
      cooldownMs: 200,
      variants: [],
      source: 'voice-soundboard',
      voiceSoundboardEffect: 'click',
    },
    {
      id: 'ui_pop',
      tags: ['ui', 'light'],
      domain: 'sfx',
      intensity: 'low',
      mood: ['neutral', 'positive'],
      durationClass: 'oneshot',
      cooldownMs: 300,
      variants: [],
      source: 'voice-soundboard',
      voiceSoundboardEffect: 'pop',
    },
    {
      id: 'ui_whoosh',
      tags: ['ui', 'transition'],
      domain: 'sfx',
      intensity: 'low',
      mood: ['neutral'],
      durationClass: 'oneshot',
      cooldownMs: 500,
      variants: [],
      source: 'voice-soundboard',
      voiceSoundboardEffect: 'whoosh',
    },
    // Alerts
    {
      id: 'alert_warning',
      tags: ['alert', 'caution'],
      domain: 'sfx',
      intensity: 'medium',
      mood: ['tense', 'caution'],
      durationClass: 'oneshot',
      cooldownMs: 3000,
      variants: [],
      source: 'voice-soundboard',
      voiceSoundboardEffect: 'warning',
    },
    {
      id: 'alert_critical',
      tags: ['alert', 'danger'],
      domain: 'sfx',
      intensity: 'high',
      mood: ['dread', 'danger'],
      durationClass: 'oneshot',
      cooldownMs: 5000,
      variants: [],
      source: 'voice-soundboard',
      voiceSoundboardEffect: 'critical',
    },
    {
      id: 'alert_info',
      tags: ['alert', 'info'],
      domain: 'sfx',
      intensity: 'low',
      mood: ['neutral', 'calm'],
      durationClass: 'oneshot',
      cooldownMs: 1000,
      variants: [],
      source: 'voice-soundboard',
      voiceSoundboardEffect: 'info',
    },
    // Ambient layers
    {
      id: 'ambient_rain',
      tags: ['weather', 'calm'],
      domain: 'ambient',
      intensity: 'low',
      mood: ['calm', 'melancholy'],
      durationClass: 'long-loop',
      cooldownMs: 0,
      variants: [],
      source: 'voice-soundboard',
      voiceSoundboardEffect: 'rain',
    },
    {
      id: 'ambient_white_noise',
      tags: ['background'],
      domain: 'ambient',
      intensity: 'low',
      mood: ['neutral'],
      durationClass: 'long-loop',
      cooldownMs: 0,
      variants: [],
      source: 'voice-soundboard',
      voiceSoundboardEffect: 'white_noise',
    },
    {
      id: 'ambient_drone',
      tags: ['dark', 'tension'],
      domain: 'ambient',
      intensity: 'medium',
      mood: ['dread', 'tension'],
      durationClass: 'long-loop',
      cooldownMs: 0,
      variants: [],
      source: 'voice-soundboard',
      voiceSoundboardEffect: 'drone',
    },
  ],
};
