// fixture-path.ts — the one thing all three C0 suites share.
//
// Deliberately NOT a `.test.ts`. Importing a value from a test file drags that
// file's `describe` blocks into the importing module's graph, so the intake
// suite ran once per importer — three concurrent copies racing on the same
// temp filenames, which failed only when the C0 files were run as a filtered
// subset and passed in the full suite. A shared constant belongs in a module,
// not in a test.

import * as path from 'node:path';

/**
 * The exported ContentPack, committed byte-for-byte as world-forge's
 * `exportToEngine` produced it. Regenerated by
 * `world-forge/packages/export-ai-rpg/src/__tests__/c0-export-table.test.ts`.
 */
export const FIXTURE_PACK_PATH = path.resolve(
  import.meta.dirname,
  '../__fixtures__/c0-forge-pack.json',
);

let scratchCounter = 0;

/**
 * A collision-free scratch path for a probe that must write a doctored pack to
 * disk and load it back through the real `loadContentFromFile`.
 *
 * Unique per process and per call. The filename never enters a measurement, so
 * this does not weaken the cycle's determinism rule — the alternative (a fixed
 * name) is what actually broke, twice, under parallel workers.
 */
export function scratchPackPath(label: string): string {
  scratchCounter += 1;
  return path.resolve(
    import.meta.dirname,
    `../__fixtures__/c0-${label}.${process.pid}.${scratchCounter}.tmp.json`,
  );
}
